# Generated by Django 5.1.1 on 2024-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('passwordHash', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': (True,),
            },
        ),
    ]
