# Generated by Django 5.1.1 on 2024-10-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
