# Generated by Django 5.1.1 on 2024-11-14 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 11, 49, 1, 323238, tzinfo=datetime.timezone.utc)),
        ),
    ]
