# Generated by Django 5.1.1 on 2024-12-05 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cartitem_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 13, 23, 56, 687965, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='ticket_category',
            field=models.CharField(choices=[('normal', 'Normalny'), ('discount', 'Ulgowy')], max_length=50),
        ),
    ]
