# Generated by Django 5.1.1 on 2024-09-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
                ('seats', models.JSONField(blank=True, default=list)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockedRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rows.row')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
