# Generated by Django 5.1.1 on 2024-10-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0002_blockedrow_blocked_at_blockedrow_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='slug',
        ),
    ]
