# Generated by Django 5.1.1 on 2024-10-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0003_remove_row_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='seats',
        ),
    ]
