# Generated by Django 5.1.1 on 2024-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0005_row_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='row',
            name='name',
        ),
        migrations.AddField(
            model_name='row',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
