# Generated by Django 5.1.1 on 2024-10-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0006_alter_row_options_remove_row_name_row_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='row',
            old_name='number',
            new_name='name',
        ),
    ]
