# Generated by Django 5.1.1 on 2024-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0007_alter_row_options_rename_number_row_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
