# Generated by Django 5.1.1 on 2024-10-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0008_alter_row_name'),
        ('sectors', '0006_remove_sector_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('sector', 'name')},
        ),
    ]
