# Generated by Django 5.1.1 on 2024-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0009_alter_row_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
