# Generated by Django 5.1.1 on 2024-11-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0010_row_row_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedRow',
        ),
    ]
