# Generated by Django 5.1.1 on 2024-10-03 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_place'),
        ('tickets', '0002_remove_ticket_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('normal', 'Normalny'), ('discount', 'Ulgowy')], default='normal', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'ordering': ['event', 'category'],
                'unique_together': {('event', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
