# Generated by Django 5.1.1 on 2024-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketcategory_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
