# Generated by Django 5.1.1 on 2024-10-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticketcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='available_quantity',
        ),
    ]
