# Generated by Django 5.1.1 on 2024-10-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticketcategory_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='price',
        ),
    ]
