# Generated by Django 5.1.1 on 2024-10-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcategory',
            name='price',
        ),
    ]
