# Generated by Django 5.1.1 on 2024-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticketcategory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
    ]
