# Generated by Django 5.1.1 on 2024-11-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketcategory_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['category']},
        ),
        migrations.AlterUniqueTogether(
            name='ticketcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='price',
        ),
    ]
