# Generated by Django 5.1.1 on 2024-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_remove_seat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
