# Generated by Django 5.1.1 on 2024-10-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_stadiumphoto'),
        ('seats', '0003_seat_is_available'),
        ('sectors', '0006_remove_sector_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sectors.sector'),
            preserve_default=False,
        ),
    ]
