# Generated by Django 5.1.1 on 2024-11-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rows', '0010_row_row_number'),
        ('seats', '0005_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row', 'seat_number']},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'seat_number')},
        ),
    ]
