# Generated by Django 5.1.1 on 2024-11-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0006_alter_seat_options_alter_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedSeat',
        ),
    ]
