# Generated by Django 5.1.1 on 2024-10-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('sectors', '0002_remove_sector_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='event',
        ),
        migrations.AddField(
            model_name='sector',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
    ]
