# Generated by Django 5.1.1 on 2024-10-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('sectors', '0003_remove_sector_event_sector_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place'),
        ),
    ]
