# Generated by Django 5.1.1 on 2024-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0004_alter_sector_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
