# Generated by Django 5.1.1 on 2024-10-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0005_sector_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='price',
        ),
    ]
