# Generated by Django 5.1.1 on 2024-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0007_alter_sector_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
